- uid: "T01_Supply_Trans_Bar"
  # 关联文案 (指向 text_patterns.yaml)
  theme_key: "Block Area Segment Distribution"
  function_key: "Supply-Transaction Unit Statistic"
  # 核心解耦：在这里选择版式！
  layout_type: "single_column_bar"
  summary_item: 1
  # 在这里选择样式
  style_config_id: "marketing_orange_green"
  # 数据映射
  data_keys:
    chart_main: "supply_trans_data"

- uid: "T02_Supply_Trans_Line"
  # 关联文案 (指向 text_patterns.yaml)
  theme_key: "Block Area Segment Distribution"
  function_key: "Supply-Transaction Unit Statistic"
  # 核心解耦：在这里选择版式！
  layout_type: "single_column_line"
  summary_item: 1
  # 在这里选择样式
  style_config_id: "marketing_orange_green"
  # 数据映射
  data_keys:
    chart_main: "supply_trans_data"
