name: Check Commit Messages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Commitizen
        run: pip install commitizen

      - name: Run Commitizen Check
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            cz check --rev-range ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
          elif [ "${{ github.event_name }}" == "push" ]; then
            cz check --rev-range ${{ github.event.before }}..${{ github.sha }}
          fi

  check-branch-name:
    name: Check Branch Name
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Print Branch Name
        run: echo "Current branch is ${{ github.event.pull_request.head.ref }}"

      - name: Check Branch Name Compliance
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          PATTERN="^(feature|feat|fix|bugfix|hotfix|release|chore|docs)/.+"

          if [[ ! $BRANCH_NAME =~ $PATTERN ]]; then
            echo "❌ Error: Branch name '$BRANCH_NAME' does not follow the standard."
            echo "Allowed types: feature/, fix/, hotfix/, release/, chore/, docs/ ..."
            echo "Example: feature/add-new-button"
            exit 1
          else
            echo "✅ Branch name is valid."
          fi
